dist: trusty

language: java

jdk:
  - openjdk8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - gcc-5
      - g++-5

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.5.0/bazel_0.5.0-linux-x86_64.deb
  - sudo dpkg -i bazel_0.5.0-linux-x86_64.deb

script:
  - bazel build ... --verbose_failures
  - bazel test ...
